### ISSUE TITLE
Skeleton update

### ISSUE THREAD

**Issue by gadicc** [graphql-accounts/graphql-accounts#1]
@TimMikeladze, ok wow, think that's everything!  Latest version of all packages; everything we'll need, babel, eslint, coveralls, mocha, etc, etc.  I should make a repo just for all that :>  CircleCI & coveralls all setup and working (ignore the "coverage unknown" on the README, github caches too aggressively - you can click on it for the coveralls page).

**Client**

As discussed this is a fullstack package.  That's my preference but it's not a huge issue for me to split back to two packages if it feels uncomfortable (I do think one is simpler though for both us and users).  The imports would be:

```js
// Server
import Accounts from "graphql-accounts";

// Client
import Accounts from "graphql-acounts/lib/client";
```

**babelrc**

Uses `es2015-node4` preset for the server (using native generators) since even Meteor uses that now.  Client uses `es2015` and `regenerator`.  Added `async` plugins and `object-rest-spread`.

**Our names**

I just went alphabetical for README, LICENSE, package.json.  Hope that's ok :)

**eslint**

Using the defaults.  If we come across anything that's uncomfortable, we can probably just change it (but let's disable specific rules inline as a preference whenever possible).  I thiiiink the async/await stuff is all included as part of `babel-eslint` but let me know if anything's not working.

**testing**

As discussed, tests are adjacent to source with a `.spec.js` extension.  I included a sample file with all the utils we'll need (sinon, chai-as-promised).  You said you were ok with `should` vs `expect`.  I definitely prefer that but I feel it's personal and that maybe `expect` might be better for lots of collaboration.  All it really boils down to is that since `should` works on objects, the syntax gets more awkward for checking `null` and `undefined`.

```js
something.should.exist();       // throws otherwise & blocks other assertions in same it()
something.should.not.exist();   // apparently works in async callbacks in node
should.not.exist(something);    // guaranteed to work for null or undefined
should.equal(something, null);  // guaranteed check for null specifically
```

I don't usually include IDE/editor configs etc but I included a `wallaby.js` since it's really awesome and if you don't use it yet you should try it it will change your life :)  And encourages more attention to tests, etc.

Let me know if you have any comments or if anything goes wrong during use.

**Comment by TimMikeladze** [comment]
👍  Everything looks great.
